country1="";
s="";
p="";
function preload(){
    
}

    // Your web app's Firebase configuration
  //var firebaseConfig = {
    //apiKey: "AIzaSyCA4DYYX3I5t1IGkM6NSz6uuRj5b36LHYk",
    //authDomain: "xyzzz-be8ff.firebaseapp.com",
    //projectId: "xyzzz-be8ff",
    //storageBucket: "xyzzz-be8ff.appspot.com",
    //messagingSenderId: "187391139929",
    //appId: "1:187391139929:web:c67ea479d27faa6f4c1148"
 // };
 // const app =firebase.initializeApp(firebaseConfig);
function submit(){
country1=document.getElementById("Country").value;
s=document.getElementById("surveylength").value;
p=document.getElementById("incidencerate").value;
localStorage.setItem("country",country1);
localStorage.setItem("Surveylength",s);
localStorage.setItem("Incidence Rate",p);
//firebase.database().ref("/").child(country1).update({
    //purpose:"adding Country"
 // });
  //firebase.database().ref("/").child(s).update({
  //  purpose:"adding survey length"
  //});
  //firebase.database().ref("/").child(p).update({
  //  purpose:"adding incidence rate"
 // });
 p0=localStorage.getItem("Incidence Rate");
 s0=localStorage.getItem("Surveylength");
 if(s0=="0-5"){
    if(p0=="1%-2%"){
     document.getElementById("data").innerHTML="$34.75"
    }
    if(p0=="3%-5%"){
     document.getElementById("data").innerHTML="$30.75"
    }
    if(p0=="6%-9%"){
     document.getElementById("data").innerHTML="$27.75"
    }
    if(p0=="10%-14%"){
     document.getElementById("data").innerHTML="$26.75"
    }
    if(p0=="15%-19%"){
     document.getElementById("data").innerHTML="$24.75"
    }
    if(p0=="20%-29%"){
     document.getElementById("data").innerHTML="$22.75"
    }
    if(p0=="30%-39%"){
     document.getElementById("data").innerHTML="$22.25"
    }
    if(p0=="40%-49%"){
     document.getElementById("data").innerHTML="$21.75"
    }
    if(p0=="50%-59%"){
     document.getElementById("data").innerHTML="$20.75"
    }
    if(p0=="60%-69%"){
     document.getElementById("data").innerHTML="$18.75"
    }
    if(p0=="70%-79%"){
     document.getElementById("data").innerHTML="$17.75"
    }
    if(p0=="80%-89%"){
     document.getElementById("data").innerHTML="$16.75"
    }
    if(p0=="90%-100%"){
     document.getElementById("data").innerHTML="$14.75"
    }
 }
 if(s0=="6-10"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$35.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$31.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$28.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$27.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$25.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$23.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$22.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$22.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$21.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$19.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$18.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$17.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$15.25"
     }
     
  }
  if(s0=="10-15"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$36.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$32.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$29.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$28.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$26.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$24.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$23.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$23.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$22.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$20.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$19.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$18.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$16.25"
     }
  }
  if(s0=="16-20"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$36.75"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$32.75"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$29.75"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$28.75"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$26.75"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$24.75"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$24.25"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$23.75"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$22.75"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$20.75"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$19.75"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$18.75"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$16.75"
     }
  }
  if(s0=="21-25"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$37.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$33.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$30.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$29.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$27.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$25.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$24.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$24.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$23.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$21.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$20.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$19.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$17.25"
     }
  }
  if(s0=="26-30"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$38.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$34.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$31.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$30.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$28.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$26.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$25.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$25.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$24.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$22.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$21.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$20.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$18.25"
     }
  }
  if(s0=="31-35"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$39.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$35.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$32.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$31.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$29.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$27.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$26.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$26.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$25.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$23.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$22.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$21.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$19.25"
     }
  }
  if(s0=="36-40"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$40.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$36.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$33.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$32.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$30.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$28.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$27.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$27.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$26.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$24.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$23.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$22.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$20.25"
     }
  }
  if(s0=="40-45"){
     if(p0=="1%-2%"){
         document.getElementById("data").innerHTML="$41.25"
     }
     if(p0=="3%-5%"){
         document.getElementById("data").innerHTML="$37.25"
     }
     if(p0=="6%-9%"){
         document.getElementById("data").innerHTML="$34.25"
     }
     if(p0=="10%-14%"){
         document.getElementById("data").innerHTML="$33.25"
     }
     if(p0=="15%-19%"){
         document.getElementById("data").innerHTML="$31.25"
     }
     if(p0=="20%-29%"){
         document.getElementById("data").innerHTML="$29.25"
     }
     if(p0=="30%-39%"){
         document.getElementById("data").innerHTML="$28.75"
     }
     if(p0=="40%-49%"){
         document.getElementById("data").innerHTML="$28.25"
     }
     if(p0=="50%-59%"){
         document.getElementById("data").innerHTML="$27.25"
     }
     if(p0=="60%-69%"){
         document.getElementById("data").innerHTML="$25.25"
     }
     if(p0=="70%-79%"){
         document.getElementById("data").innerHTML="$24.25"
     }
     if(p0=="80%-89%"){
         document.getElementById("data").innerHTML="$23.25"
     }
     if(p0=="90%-100%"){
         document.getElementById("data").innerHTML="$21.25"
     }
  }

}
